name: prismalaser
services:
  frontend:
    container_name: prismalaser-frontend
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3333:3000

