import { GoogleTagManager } from '@next/third-parties/google';
import { Geist, Geist_Mono } from 'next/font/google';

import { StoreProvider } from './StoreProvider';
import type { Metadata } from 'next';

import './globals.css';
import './tailwind.css';
import 'reactflow/dist/style.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <title>Prismalaser - Editor/Visualization</title>
          <meta name="description" content="Prisma schema visualization, editor and more" />
          <meta
            name="keywords"
            content="Prisma, Prisma ORM, Schema, Visualization, React Flow, Prisma Schema Visualization"
          />
          <link rel="icon" href="/favicon.ico" sizes="any" />
          <meta name="theme-color" content="#1e1e1e" />
          {/* OpenGraph */}
          <meta property="og:type" content="object" />
          <meta property="og:site_name" content="Prismalaser" />
          <meta property="og:title" content="Prismalaser" />
          <meta property="og:description" content="Prisma schema visualization, editor and more" />
          <meta property="og:image" content="/img/og-banner.png" />
          <meta property="og:image:width" content="1200" />
          <meta property="og:image:height" content="630" />
          <meta property="og:image:alt" content="Prismalaser - schema visualization and more" />
        </head>
        <GoogleTagManager gtmId="GTM-T7999C3W" />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
